import {test,expect} from '@playwright/test';
test('owner creates clients and invites a viewer with an isolated embedded agenda',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByLabel('E-mail',{exact:true}).fill('owner@folks.test');await page.getByLabel('Senha de acesso').fill('ui-test-password');await page.getByRole('button',{name:'Entrar na agenda'}).click();
 await page.getByRole('button',{name:'Gerenciar workspaces',exact:true}).click();
 await page.getByRole('button',{name:'Novo workspace',exact:true}).click();await page.getByLabel('Nome do cliente').fill('Clínica Aurora');await page.getByRole('button',{name:'Criar workspace',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.workspace-detail h2')).toHaveText('Clínica Aurora');
 await page.getByLabel('Origens autorizadas do HELENA').fill('https://crm.example.com');await page.getByRole('button',{name:'Salvar configurações'}).click();await expect(page.getByRole('status')).toContainText('Configurações salvas');
 const embedLink=await page.getByLabel('Link para incorporar').inputValue();expect(embedLink).toContain('workspace=');expect(embedLink).toContain('embed=1');
 await page.getByLabel('E-mail do convidado').fill('recepcao@aurora.test');await page.getByLabel('Permissão',{exact:true}).selectOption('viewer');await page.getByRole('button',{name:'Gerar convite'}).click();
 const inviteLink=await page.getByLabel('Link do convite').inputValue();expect(inviteLink).toContain('#invite=');
 await page.screenshot({path:'test-results/workspaces-desktop.png',fullPage:true});
 await page.locator('.workspace-card').filter({has:page.getByRole('heading',{name:'Clínica Aurora',exact:true})}).getByRole('button',{name:'Abrir agenda'}).click();
 await page.getByRole('button',{name:'Novo evento',exact:true}).click();await page.getByLabel('Título do evento').fill('Consulta Aurora');await page.getByRole('button',{name:'Salvar evento'}).click();await expect(page.locator('.event-chip')).toContainText('Consulta Aurora');
 await page.getByLabel('Selecionar workspace').selectOption({label:'Folks'});await expect(page.locator('.event-chip').filter({hasText:'Consulta Aurora'})).toHaveCount(0);
 const viewerContext=await browser.newContext();const viewer=await viewerContext.newPage();viewer.on('pageerror',e=>errors.push(e.message));
 await viewer.goto(inviteLink);await expect(viewer.getByLabel('E-mail',{exact:true})).toHaveValue('recepcao@aurora.test');await viewer.getByLabel('Seu nome').fill('Recepção Aurora');await viewer.getByLabel('Crie sua senha').fill('senha-longa-da-recepcao');await viewer.getByRole('button',{name:'Aceitar convite e entrar'}).click();
 await expect(viewer.locator('.event-chip')).toContainText('Consulta Aurora');await expect(viewer.getByRole('button',{name:'Novo evento',exact:true})).toHaveCount(0);await expect(viewer.getByRole('button',{name:'Automações',exact:true})).toHaveCount(0);
 await viewer.locator('.event-chip').first().click();await expect(viewer.getByLabel('Título do evento')).toBeDisabled();await expect(viewer.getByRole('button',{name:'Salvar evento'})).toHaveCount(0);await viewer.getByRole('button',{name:'Fechar',exact:true}).click();
 await viewer.goto(embedLink);await expect(viewer.locator('.sidebar')).toHaveCount(0);await expect(viewer.locator('.event-chip')).toContainText('Consulta Aurora');
 await viewer.goto(page.url());await expect(viewer.getByRole('heading',{name:'Workspace indisponível'})).toBeVisible();await expect(viewer.locator('.event-chip')).toHaveCount(0);
 await page.getByRole('button',{name:'Gerenciar workspaces',exact:true}).click();await page.getByRole('button',{name:'Gerenciar Clínica Aurora',exact:true}).click();
 await page.getByLabel('Permissão de recepcao@aurora.test').selectOption('editor');await expect(page.getByRole('status')).toContainText('Permissão atualizada');
 await viewer.goto(embedLink);await expect(viewer.getByRole('button',{name:'Novo evento',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/workspaces-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Remover recepcao@aurora.test'}).click();await expect(page.getByRole('status')).toContainText('Acesso removido');
 await viewer.reload();await expect(viewer.getByRole('heading',{name:'Seu acesso está pronto.'})).toBeVisible();await expect(viewer.locator('.event-chip')).toHaveCount(0);
 await viewerContext.close();expect(errors).toEqual([]);
});
