import React,{useState,useEffect} from 'react';
import {Copy} from 'lucide-react';
import GoogleCalendar from './GoogleCalendar';
const triggers={'event.created':'Ao criar evento','event.updated':'Ao atualizar evento','event.deleted':'Ao excluir evento','event.reminder':'Antes do evento','event.started':'No início do evento'};
const vars={nome:'Nome do cliente',responsavel:'Nome do responsável',titulo:'Título do evento',data:'Data',hora:'Horário',fim:'Horário de término',local:'Local ou link',descricao:'Descrição',email:'E-mail',contato:'ID no CRM',telefone:'WhatsApp do cliente'};
export default function HelenaAutomations({api,hooks,onRefresh,workspaceId,mode='all',onOpenIntegrations=()=>{const url=new URL(location.href);url.searchParams.set('section','integrations');location.href=url;}}) {
 const activeMode=mode==='all'&&new URLSearchParams(location.search).get('section')==='integrations'?'integrations':mode;
 const [connected,setConnected]=useState(false),[token,setToken]=useState(''),[channelList,setChannels]=useState([]),[models,setModels]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[webhookUrl,setWebhookUrl]=useState(''),[busy,setBusy]=useState(false),[loadingModels,setLoadingModels]=useState(false);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function copy(value){try{await navigator.clipboard.writeText(value);setNotice('Link do webhook copiado.');}catch{setNotice('Selecione e copie o link manualmente.');}}
 useEffect(()=>{let current=true;api('/helena').then(async c=>{if(!current)return;setConnected(c.connected);setWebhookUrl(c.webhookUrl || '');if(c.connected){const list=await api('/helena/channels');if(current)setChannels(list);}}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[workspaceId]);
 useEffect(()=>{let current=true;setModels([]);if(!editing?.channelId)return;setLoadingModels(true);api('/helena/templates?channelId='+encodeURIComponent(editing.channelId)).then(data=>{if(current)setModels(data);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoadingModels(false);});return()=>{current=false;};},[editing?.channelId]);
 const update=(key,value)=>setEditing(e=>({...e,[key]:value}));
 const selected=models.find(m=>m.id===editing?.templateId);
 const helenaHooks=hooks.filter(h=>h.kind==='helena');
 return <>{activeMode!=='automations'&&<GoogleCalendar workspaceId={workspaceId} api={api}/>}<section className="helena-panel">
  <div className="section-heading"><div><h3>{activeMode==='integrations'?'HELENA CRM':'Mensagens pelo HELENA'}</h3><p>{activeMode==='integrations'?'Conecte a conta e configure o retorno de eventos para o FolkSales.':'Escolha o modelo e quando enviar. A agenda executa as regras automaticamente.'}</p></div><span className="badge">{connected?'Conectado':'Não conectado'}</span></div>
  {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-message" role="status">{notice}</p>}
  {activeMode!=='automations'&&<details open={!connected}><summary>{connected?'Gerenciar conexão':'Conectar conta HELENA'}</summary><form onSubmit={e=>{e.preventDefault();act(async()=>{const result=await api('/helena',{method:'PUT',body:JSON.stringify({token})});setConnected(true);setWebhookUrl(result.webhookUrl || '');setToken('');setChannels(result.channels);setEditing(null);await onRefresh();setNotice('Conexão salva. Ao trocar o token, as regras são pausadas para revisão.');});}}>
   <label>Token da conta HELENA<input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} required placeholder="Cole o token de Ajustes → Integrações"/></label><button className="outline" disabled={busy}>{connected?'Substituir token e pausar regras':'Conectar e carregar canais'}</button>
   {connected&&<button type="button" className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Desconectar o HELENA e pausar as regras deste workspace?'))act(async()=>{await api('/helena',{method:'DELETE'});setConnected(false);setWebhookUrl('');setChannels([]);setEditing(null);await onRefresh();});}}>Desconectar</button>}
  </form></details>}
  {activeMode!=='automations'&&connected&&<label className="helena-webhook-url">Webhook de respostas do HELENA<div className="copy-row"><input aria-label="URL do webhook de respostas do HELENA" readOnly value={webhookUrl}/><button type="button" className="outline" aria-label="Copiar webhook do HELENA" onClick={()=>copy(webhookUrl)} disabled={!webhookUrl}><Copy size={15}/></button></div><small>Cadastre este endereço no HELENA para receber o clique em “Verificar Relatório”.</small></label>}
  {activeMode==='automations'&&!connected&&<div className="integration-needed"><p>Conecte o HELENA CRM antes de criar regras de mensagem.</p><button className="outline" onClick={onOpenIntegrations}>Abrir integrações</button></div>}
  {activeMode!=='integrations'&&connected&&<><div className="helena-rules">{helenaHooks.map(h=><article className="helena-rule" key={h.id}><div><strong>{h.name}</strong><p>{h.templateName} · {h.recipient==='assignee'?'Responsável':'Cliente'}</p><small>{h.triggers.map(t=>triggers[t]+(t==='event.reminder'?` (${h.reminderMinutes} min)`:'')).join(' · ')}</small></div><span>{h.enabled?'Ativa':'Pausada'}</span><button className="outline" disabled={busy} onClick={()=>{setError('');setEditing({...h});}}>Configurar</button><button className="outline" disabled={busy} onClick={()=>act(async()=>{await api('/hooks/'+h.id,{method:'PUT',body:JSON.stringify({...h,enabled:!h.enabled})});await onRefresh();})}>{h.enabled?'Pausar':'Ativar'}</button></article>)}</div>
   {!editing&&<button className="primary" disabled={busy} onClick={()=>setEditing({kind:'helena',name:'',channelId:channelList[0]?.id || '',templateId:'',parameters:{},recipient:'contact',triggers:['event.created'],reminderMinutes:1440,timezone:'America/Manaus',categories:[],enabled:false,fileIdOrUrl:''})}>Nova regra de mensagem</button>}
  </>}
  {activeMode!=='integrations'&&editing&&<form className="helena-editor" onSubmit={e=>{e.preventDefault();act(async()=>{await api('/hooks'+(editing.id?'/'+editing.id:''),{method:editing.id?'PUT':'POST',body:JSON.stringify(editing)});setEditing(null);await onRefresh();setNotice('Regra salva.');});}}>
   <h3>{editing.id?'Configurar regra':'Nova regra de mensagem'}</h3>
   <label>Nome da regra<input required maxLength={100} value={editing.name} onChange={e=>update('name',e.target.value)} placeholder="Ex.: Lembrete de 24 horas"/></label>
   <div className="form-row"><label>Canal de WhatsApp<select required value={editing.channelId} onChange={e=>setEditing({...editing,channelId:e.target.value,templateId:'',parameters:{}})}><option value="">Selecione</option>{channelList.map(c=><option key={c.id} value={c.id}>{c.name} · {c.number}</option>)}</select></label>
   <label>Modelo aprovado<select required disabled={loadingModels} value={editing.templateId} onChange={e=>{const m=models.find(m=>m.id===e.target.value);setEditing({...editing,templateId:e.target.value,parameters:Object.fromEntries((m?.params || []).map(p=>[p.name,''])),fileIdOrUrl:''});}}><option value="">{loadingModels?'Carregando…':'Selecione o modelo'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div>
   {selected&&<><pre className="template-preview">{selected.text}</pre><p className="form-hint">Preencha cada variável usando um dado do evento ou um texto fixo.</p>{selected.params.map(p=><div className="form-row" key={p.name}><label>Variável {p.name}<input required value={editing.parameters[p.name] || ''} onChange={e=>update('parameters',{...editing.parameters,[p.name]:e.target.value})} placeholder="Texto fixo ou {{nome}}"/></label><label>Usar dado do evento<select value="" onChange={e=>{if(e.target.value)update('parameters',{...editing.parameters,[p.name]:'{{'+e.target.value+'}}'});}}><option value="">Escolher campo…</option>{Object.entries(vars).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>)}{selected.fileType&&selected.fileType!=='UNDEFINED'&&<label>Arquivo do modelo (URL HTTPS ou ID)<input required value={editing.fileIdOrUrl} onChange={e=>update('fileIdOrUrl',e.target.value)}/></label>}</>}
   <div className="form-row"><label>Destinatário<select value={editing.recipient} onChange={e=>update('recipient',e.target.value)}><option value="contact">Cliente do evento</option><option value="assignee">Responsável pelo evento</option></select></label><label>Fuso das mensagens<select value={editing.timezone} onChange={e=>update('timezone',e.target.value)}>{['America/Manaus','America/Sao_Paulo','America/Fortaleza','America/Belem','America/Cuiaba','America/Rio_Branco','America/Noronha','UTC'].map(t=><option key={t}>{t}</option>)}</select></label></div>
   <label>Quando enviar</label><div className="trigger-options">{Object.entries(triggers).map(([key,label])=><label className="inline-check" key={key}><input type="checkbox" checked={editing.triggers.includes(key)} onChange={()=>update('triggers',editing.triggers.includes(key)?editing.triggers.filter(t=>t!==key):[...editing.triggers,key])}/>{label}</label>)}</div>
   {editing.triggers.includes('event.reminder')&&<label>Antecedência do lembrete<select value={editing.reminderMinutes} onChange={e=>update('reminderMinutes',Number(e.target.value))}>{[[5,'5 minutos'],[15,'15 minutos'],[30,'30 minutos'],[60,'1 hora'],[120,'2 horas'],[1440,'24 horas']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>}
   <label>Aplicar aos eventos da agenda<select value={editing.categories[0] || ''} onChange={e=>update('categories',e.target.value?[e.target.value]:[])}><option value="">Todas</option><option value="meeting">Reuniões</option><option value="task">Tarefas</option><option value="personal">Pessoal</option></select></label>
   <label className="inline-check"><input type="checkbox" checked={editing.enabled} onChange={e=>update('enabled',e.target.checked)}/>Regra ativa — enviar automaticamente nos gatilhos selecionados</label>
   <p className="form-hint">Informe o nome e o WhatsApp do destinatário no evento. Lembretes usam a antecedência desta regra. O histórico diferencia envios aceitos de entregas confirmadas.</p>
   <div className="form-footer">{editing.id&&<button type="button" className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Excluir esta regra e cancelar os envios pendentes?'))act(async()=>{await api('/hooks/'+editing.id,{method:'DELETE'});setEditing(null);await onRefresh();});}}>Excluir regra</button>}<button type="button" className="outline" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy || loadingModels || !selected || !editing.triggers.length}>{busy?'Salvando…':'Salvar regra'}</button></div>
  </form>}
 </section></>;
}
