import React, {useEffect, useState, useRef} from 'react';
import {ArrowUpRight, LoaderCircle, LogOut, KeyRound, ArrowLeft} from 'lucide-react';
import {request, roleNames} from './api';
import Calendar from './Calendar';
import WorkspaceManager from './WorkspaceManager';
export function Brand(){return <div className="brand"><span className="brand-mark">f</span>folks<span>calendar</span></div>;}
function Login({onLogin}) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <div className="login"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await request('/login',{method:'POST',body:JSON.stringify({email,password})}));}catch(e){setError(e.message);}finally{setBusy(false);}}}><Brand/><h1>Seu tempo, bem conectado.</h1><p>Entre com sua conta para acessar os workspaces da sua equipe.</p><label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha de acesso<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar na agenda'}<ArrowUpRight size={16}/></button><small className="login-note">Primeiro acesso? Abra o convite enviado pela administração do seu workspace.</small></form></div>;
}
function AcceptInvite({token,onLogin,onCancel}) {
  const [invite,setInvite]=useState(null),[error,setError]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{request('/invites/'+encodeURIComponent(token)).then(setInvite).catch(e=>setError(e.message));},[token]);
  return <div className="login"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data=await request('/invites/'+encodeURIComponent(token)+'/accept',{method:'POST',body:JSON.stringify({name,password})});onLogin(data);}catch(e){setError(e.message);}finally{setBusy(false);}}}><Brand/><h1>{invite?'Você tem um lugar aqui.':'Convite para o workspace'}</h1>{invite&&<><p>Você foi convidado para <strong>{invite.workspaceName}</strong> como <strong>{roleNames[invite.role]}</strong>.</p><label>E-mail<input readOnly type="email" value={invite.email}/></label>{!invite.existingAccount&&<label>Seu nome<input autoComplete="name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>}<label>{invite.existingAccount?'Senha da sua conta':'Crie sua senha'}<input type="password" autoComplete={invite.existingAccount?'current-password':'new-password'} minLength={invite.existingAccount?1:12} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="form-hint">{invite.existingAccount?'Use sua senha atual. O convite adiciona este workspace à sua conta.':'Use pelo menos 12 caracteres. Você terá um login individual.'}</p><button className="primary" disabled={busy}>{busy?'Confirmando…':'Aceitar convite e entrar'}<ArrowUpRight size={16}/></button></>}{error&&<p className="form-error" role="alert">{error}</p>}<button type="button" className="text-button" onClick={onCancel}>Voltar para o login</button></form></div>;
}
function PasswordForm({onClose,onChanged}) {
  const [currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <div className="login"><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/me/password',{method:'POST',body:JSON.stringify({currentPassword,password})});onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}}><Brand/><h1>Atualizar sua senha</h1><p>Ao salvar, todas as suas sessões serão encerradas.</p><label>Senha atual<input type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label>Nova senha<input type="password" autoComplete="new-password" minLength={12} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>Salvar nova senha</button><button type="button" className="text-button" onClick={onClose}><ArrowLeft size={14}/> Voltar</button></form></div>;
}
export default function Portal(){
  const [session,setSession]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState(()=>new URLSearchParams(location.search).get('workspace')||sessionStorage.getItem('folks-workspace')||'');
  const [manage,setManage]=useState(false),[changePassword,setChangePassword]=useState(false);
  const [inviteToken,setInviteToken]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('invite'));
  const generation=useRef(0);
  function clearSession(){generation.current++;sessionStorage.removeItem('folks-token');sessionStorage.removeItem('folks-workspace');setSession(null);setManage(false);setChangePassword(false);setReady(true);}
  function choose(id){sessionStorage.setItem('folks-workspace',id);setSelected(id);const url=new URL(location.href);url.searchParams.set('workspace',id);url.hash='';history.replaceState(null,'',url);setManage(false);}
  function loggedIn(data){generation.current++;sessionStorage.setItem('folks-token',data.token);setSession(data);setReady(true);setError('');if(data.workspaceId){setInviteToken(null);choose(data.workspaceId);}else if(!new URLSearchParams(location.search).has('workspace')&&data.workspaces.length)choose(data.workspaces[0].id);}
  async function refresh(){const current=generation.current;try{const data=await request('/me');if(current!==generation.current)return;setSession(data);setError('');if(!selected&&!new URLSearchParams(location.search).has('workspace')&&data.workspaces.length)choose(data.workspaces[0].id);}catch(e){if(current===generation.current)setError(e.message);}finally{setReady(true);}}
  async function logout(){try{await request('/logout',{method:'POST'});}finally{clearSession();}}
  useEffect(()=>{const reset=()=>clearSession();window.addEventListener('folks-unauthorized',reset);if(sessionStorage.getItem('folks-token'))refresh();else setReady(true);return()=>window.removeEventListener('folks-unauthorized',reset);},[]);
  useEffect(()=>{if(!session)return;const id=setInterval(refresh,15000);return()=>clearInterval(id);},[!!session,selected]);
  const workspace=session?.workspaces.find(w=>w.id===selected);
  if(inviteToken)return <AcceptInvite token={inviteToken} onLogin={loggedIn} onCancel={()=>{setInviteToken(null);history.replaceState(null,'',location.pathname+location.search);}}/>;
  if(!ready)return <div className="login"><Brand/><LoaderCircle className="spin"/></div>;
  if(!session)return <Login onLogin={loggedIn}/>;
  if(changePassword)return <PasswordForm onClose={()=>setChangePassword(false)} onChanged={clearSession}/>;
  if(manage)return <WorkspaceManager user={session.user} workspaces={session.workspaces} initialWorkspace={selected} onBack={()=>setManage(false)} onOpen={choose} onRefresh={refresh} onLogout={logout} onPassword={()=>setChangePassword(true)}/>;
  if(!workspace)return <div className="login"><div className="no-workspace"><Brand/><h1>{session.workspaces.length?'Workspace indisponível':'Seu acesso está pronto.'}</h1><p>{session.workspaces.length?'Este link não corresponde a um workspace ao qual você tem acesso. Selecione um dos seus espaços.':'Peça um convite à administração Folks para acessar a agenda de um cliente.'}</p>{session.workspaces.map(w=><button key={w.id} className="outline" onClick={()=>choose(w.id)}>{w.name}<ArrowUpRight size={15}/></button>)}{session.user.isOwner&&<button className="primary" onClick={()=>setManage(true)}>Gerenciar workspaces</button>}<button className="text-button" onClick={logout}><LogOut size={15}/> Sair</button>{error&&<p role="alert">{error}</p>}</div></div>;
  return <><Calendar key={`${workspace.id}:${workspace.role}`} user={session.user} workspace={workspace} workspaces={session.workspaces} onSwitch={choose} onManage={()=>setManage(true)} onLogout={logout}/><button className="account-password" aria-label="Alterar minha senha" title="Alterar minha senha" onClick={()=>setChangePassword(true)}><KeyRound size={16}/></button>{error&&<div className="connection-error" role="alert">{error}<button onClick={refresh}>Reconectar</button></div>}</>;
}
