import React, {useEffect,useState,useRef} from 'react';
import {ArrowLeft, ArrowUpRight, Plus, Users, Copy, Trash2, ShieldCheck, Building2, Link2, X, LogOut, KeyRound, Check, LoaderCircle} from 'lucide-react';
import {request,roleNames,workspaceLink} from './api';
import {Brand} from './Portal';
export default function WorkspaceManager({user,workspaces,initialWorkspace,onBack,onOpen,onRefresh,onLogout,onPassword}) {
  const editable=workspaces.filter(w=>['owner','admin'].includes(w.role));
  const [active,setActive]=useState(initialWorkspace),[creating,setCreating]=useState(false),[newName,setNewName]=useState('');
  const [members,setMembers]=useState([]),[invites,setInvites]=useState([]),[name,setName]=useState(''),[origins,setOrigins]=useState('');
  const [email,setEmail]=useState(''),[role,setRole]=useState('editor'),[inviteLink,setInviteLink]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
  const generation=useRef(0);
  const workspace=editable.find(w=>w.id===active);
  const api=(path,options)=>request('/workspaces/'+active+path,options);
  async function load(){const seq=++generation.current;setLoading(true);try{const data=await api('/members');if(seq!==generation.current)return;setMembers(data.members);setInvites(data.invites);}catch(e){if(seq===generation.current){setMembers([]);setInvites([]);setError(e.message);}}finally{if(seq===generation.current)setLoading(false);}}
  useEffect(()=>{setMembers([]);setInvites([]);setInviteLink('');setError('');setMessage('');if(workspace){setName(workspace.name);setOrigins(workspace.origins.join('\n'));load();}return()=>{generation.current++;};},[active,workspace?.role]);
  async function action(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function copy(value){try{await navigator.clipboard.writeText(value);setMessage('Link copiado.');}catch{setMessage('Selecione e copie o link abaixo.');}}
  return <div className="management-shell"><header className="management-header"><Brand/><div><span>{user.name}</span><button className="icon" aria-label="Alterar minha senha" onClick={onPassword}><KeyRound size={17}/></button><button className="icon" aria-label="Sair" onClick={onLogout}><LogOut size={17}/></button><button className="outline" onClick={onBack}><ArrowLeft size={15}/> Voltar à agenda</button></div></header><main className="management-content"><section className="page-heading"><div><div className="eyebrow">CADA CLIENTE NO SEU ESPAÇO</div><h1>{user.isOwner?'Seus clientes, bem organizados.':'Sua equipe, conectada.'}</h1><p>Agendas independentes. As pessoas certas em cada workspace.</p></div>{user.isOwner&&<button className="primary" onClick={()=>setCreating(true)}><Plus size={17}/> Novo workspace</button>}</section><div className="workspace-grid">{workspaces.map(w=><article className={'workspace-card '+(active===w.id?'selected':'')} key={w.id}><span className="workspace-card-icon"><Building2 size={23}/></span><span className="role-badge">{roleNames[w.role]}</span><h2>{w.name}</h2><p>Eventos e automações exclusivos deste cliente.</p><footer><button className="text-button" onClick={()=>onOpen(w.id)}>Abrir agenda <ArrowUpRight size={15}/></button>{['owner','admin'].includes(w.role)&&<button className="outline" disabled={busy} aria-label={'Gerenciar '+w.name} onClick={()=>setActive(w.id)}><Users size={14}/> Gerenciar</button>}</footer></article>)}</div>
 {workspace&&<section className="workspace-detail"><header><div><div className="eyebrow">EQUIPE E ACESSO</div><h2>{workspace.name}</h2></div><span className="role-badge"><ShieldCheck size={13}/> Dados isolados por workspace</span></header>{error&&<div className="form-error" role="alert">{error}</div>}{message&&<div className="success-message" role="status"><Check size={15}/>{message}</div>}<div className="workspace-settings-grid"><form className="workspace-settings" onSubmit={e=>{e.preventDefault();action(async()=>{await api('',{method:'PATCH',body:JSON.stringify({name,origins:origins.split('\n').map(x=>x.trim()).filter(Boolean)})});await onRefresh();setMessage('Configurações salvas.');});}}><h3>Identidade e integração</h3><label>Nome do workspace<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Origens autorizadas do HELENA<textarea rows={3} placeholder={'https://seu-crm.com\nUma origem por linha, sem caminhos'} value={origins} onChange={e=>setOrigins(e.target.value)}/></label><p className="form-hint">Cole a origem da página do CRM que incorpora a agenda. Cada usuário continuará precisando de acesso a este workspace.</p><button className="outline" disabled={busy}>Salvar configurações</button><label className="embed-link-label">Link para incorporar<div className="copy-row"><input readOnly value={workspaceLink(active,true)}/><button className="outline" type="button" aria-label="Copiar link de incorporação" onClick={()=>copy(workspaceLink(active,true))}><Copy size={15}/></button></div></label></form><form className="invite-form" onSubmit={e=>{e.preventDefault();action(async()=>{const invite=await api('/invites',{method:'POST',body:JSON.stringify({email,role})});setInviteLink(`${location.origin}/#invite=${invite.token}`);setEmail('');await load();setMessage('Convite criado. Copie o link e compartilhe com a pessoa.');});}}><h3>Convide uma pessoa</h3><p>Ela usará o próprio e-mail e senha para entrar.</p><label>E-mail do convidado<input type="email" autoComplete="off" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Permissão<select aria-label="Permissão" value={role} onChange={e=>setRole(e.target.value)}><option value="admin">Administrador — equipe e automações</option><option value="editor">Editor — criar e editar eventos</option><option value="viewer">Somente leitura — consultar eventos</option></select></label><button className="primary" disabled={busy}><Plus size={15}/> Gerar convite</button><p className="form-hint">Válido por 7 dias e para um único uso. O link não é enviado por e-mail automaticamente.</p>{inviteLink&&<div className="invite-result"><label>Link do convite<div className="copy-row"><input readOnly value={inviteLink}/><button className="outline" type="button" aria-label="Copiar convite" onClick={()=>copy(inviteLink)}><Copy size={15}/></button></div></label><small>Copie agora. Por segurança, este link não será exibido novamente.</small></div>}</form></div>
 <div className="section-heading"><h3>Pessoas com acesso <span>{members.length} membros</span></h3><button onClick={load} disabled={busy||loading}>Atualizar</button></div>{loading?<div className="members-loading"><LoaderCircle className="spin" size={20}/> Carregando equipe…</div>:<div className="members-list">{members.map(member=><div className="member-row" key={member.id}><span className="member-avatar">{member.name[0].toUpperCase()}</span><div className="member-info"><strong>{member.name}{member.id===user.id?' (você)':''}</strong><small>{member.email}</small></div>{member.isOwner||member.id===user.id?<span className="role-badge">{roleNames[member.role]}</span>:<><select aria-label={'Permissão de '+member.email} value={member.role} disabled={busy} onChange={e=>action(async()=>{await api('/members/'+member.id,{method:'PATCH',body:JSON.stringify({role:e.target.value})});await load();setMessage('Permissão atualizada.');})}><option value="admin">Administrador</option><option value="editor">Editor</option><option value="viewer">Somente leitura</option></select><button className="icon danger" disabled={busy} aria-label={'Remover '+member.email} onClick={()=>{if(window.confirm('Remover o acesso de '+member.name+' a este workspace?'))action(async()=>{await api('/members/'+member.id,{method:'DELETE'});await load();setMessage('Acesso removido deste workspace.');});}}><Trash2 size={16}/></button></>}</div>)}</div>}
 {invites.length>0&&<><h3 className="pending-heading">Convites pendentes</h3><div className="members-list">{invites.map(invite=><div className="member-row" key={invite.id}><span className="member-avatar"><Link2 size={16}/></span><div className="member-info"><strong>{invite.email}</strong><small>Expira em {new Date(invite.expires).toLocaleDateString('pt-BR')}</small></div><span className="role-badge">{roleNames[invite.role]}</span><button className="icon danger" aria-label={'Revogar convite de '+invite.email} disabled={busy} onClick={()=>action(async()=>{await api('/invites/'+invite.id,{method:'DELETE'});setInviteLink('');await load();setMessage('Convite revogado.');})}><X size={16}/></button></div>)}</div></>}</section>}
 {!workspace&&editable.length>0&&<div className="upcoming-empty"><ShieldCheck size={24}/><p>Selecione “Gerenciar” em um workspace para configurar equipe, convites e integração.</p></div>}
 </main>{creating&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="Novo workspace"><header><div><h2>Um espaço para cada cliente</h2><p>As agendas e automações começam vazias.</p></div><button className="icon" aria-label="Fechar" onClick={()=>{setCreating(false);setError('');}}><X size={20}/></button></header><form onSubmit={e=>{e.preventDefault();action(async()=>{const created=await request('/workspaces',{method:'POST',body:JSON.stringify({name:newName})});await onRefresh();setActive(created.id);setNewName('');setCreating(false);setMessage('Workspace criado. Agora você pode convidar a equipe.');});}}><label>Nome do cliente<input autoFocus required maxLength={100} value={newName} placeholder="Ex.: Clínica Aurora" onChange={e=>setNewName(e.target.value)}/></label><p className="form-hint">Você mantém o acesso de administrador Folks. Nenhuma pessoa de outros workspaces terá acesso automaticamente.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-footer"><button type="button" className="outline" onClick={()=>setCreating(false)}>Cancelar</button><button className="primary" disabled={busy}>Criar workspace <Plus size={15}/></button></div></form></section></div>}</div>;
}
